"""create core accessguard tables

Revision ID: b6f485efbf09
Revises: 
Create Date: 2026-09-20 03:43:36.091246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6f485efbf09'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('application_owner', sa.String(length=255), nullable=True),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('criticality', sa.String(length=20), nullable=True),
    sa.Column('dormancy_threshold_days', sa.Integer(), nullable=True),
    sa.Column('reminder_before_days', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('team', sa.String(length=255), nullable=True),
    sa.Column('lead_name', sa.String(length=255), nullable=True),
    sa.Column('lead_email', sa.String(length=255), nullable=True),
    sa.Column('manager_name', sa.String(length=255), nullable=True),
    sa.Column('manager_email', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_employee_id'), ['employee_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('access_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('last_login_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_validated_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('compliance_status', sa.String(length=20), server_default='UNKNOWN', nullable=False),
    sa.Column('action_required', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'application_id', name='uq_access_record_user_application')
    )
    with op.batch_alter_table('access_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_records_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_records_user_id'), ['user_id'], unique=False)

    op.create_table('reminder_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_record_id', sa.Integer(), nullable=False),
    sa.Column('reminder_type', sa.String(length=64), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['access_record_id'], ['access_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminder_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminder_history_access_record_id'), ['access_record_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminder_history_access_record_id'))

    op.drop_table('reminder_history')
    with op.batch_alter_table('access_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_access_records_application_id'))

    op.drop_table('access_records')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_employee_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_name'))
        batch_op.drop_index(batch_op.f('ix_applications_id'))

    op.drop_table('applications')
    # ### end Alembic commands ###
